mainSections   = ["post"]
rssFullContent = true
favicon        = "img/avatar.png"

[footer]
    since = 2020

[sidebar]
    emoji    = "✏️"
    subtitle = "Sharing stuff and mistakes i have learned , also some aspects in my life."
    # avatar   = "img/avatar.png"

[article]
    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    # See complete configuration in config/_default/params.toml
    enabled  = true
    provider = "disqus"
